
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5


# test:
#   <<: *default
#   database: db/test1.sqlite3

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
