
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development1.sqlite3

test:
  <<: *default
  database: db/test1.sqlite3

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
